### PR TITLE
feat (keymanager): Angular 5 - web3/metamask-conditional welcome message

### PR DESCRIPTION
**Pull request by kcheli**
Angular 5 - added web3/metamask-conditional welcome message

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c9627fa89b9193b3cfd0d0cf2398828b80f0031e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Review by lhendre — APPROVED** [review]

**Comment by lhendre** [comment]
Any additional work needed or are we good to merge?

**Comment by kcheli** [comment]
No additional work should be needed on this feature.

**Comment by kcheli** [comment]
@lhendre ready to merge

**Pull request merged**
