### PR TITLE
[WIP]Kc metamask loginconnect error

### PR DESCRIPTION
**Pull request by kcheli**
added manual metamask connect - welcome.component.ts
edited text links - welcome.component.ts

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 27ba3a17f6993f31d45cefd2ac202c176c4af067
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 97fc9ec16d4bb1901335281ac5de75c4a448937b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9640b0d94be23604e183cdb48e8372da380a6c86
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 13eed7c42d1a40802f238332abff75a6b824ad6a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7678428c814e2362417f22793fc727032285b0da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ee9669efa7867f58ad7e83f4d6bd6a4c555593d4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a2b8b1b658e61a655681a625a573d2f0449c16e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4da5073eb3cb5e430da518f170d00a8292e2590e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 47ea93b21494a7422b2035574894e3326b37aafa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by lhendre** [comment]
You mentioned there were a bunch of new commits you weren't sure on, can you give me a commit number or specific change to look at?  Also, make sure the CNAME file is correct 
it's “keymanager.simplyvitalhealth.com” when it should be keymanager.simplyvitalhealth.com.  It likely that if you initalized something with node it may have autogenerated this stuff for you

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 27ba3a17f6993f31d45cefd2ac202c176c4af067
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 97fc9ec16d4bb1901335281ac5de75c4a448937b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9640b0d94be23604e183cdb48e8372da380a6c86
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 13eed7c42d1a40802f238332abff75a6b824ad6a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7678428c814e2362417f22793fc727032285b0da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ee9669efa7867f58ad7e83f4d6bd6a4c555593d4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a2b8b1b658e61a655681a625a573d2f0449c16e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4da5073eb3cb5e430da518f170d00a8292e2590e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 47ea93b21494a7422b2035574894e3326b37aafa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 012c939abcbf0ddf1c48db3bfa7e8ea891093b3c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 27ba3a17f6993f31d45cefd2ac202c176c4af067
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 97fc9ec16d4bb1901335281ac5de75c4a448937b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9640b0d94be23604e183cdb48e8372da380a6c86
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 13eed7c42d1a40802f238332abff75a6b824ad6a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7678428c814e2362417f22793fc727032285b0da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ee9669efa7867f58ad7e83f4d6bd6a4c555593d4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a2b8b1b658e61a655681a625a573d2f0449c16e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4da5073eb3cb5e430da518f170d00a8292e2590e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 47ea93b21494a7422b2035574894e3326b37aafa
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 012c939abcbf0ddf1c48db3bfa7e8ea891093b3c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4713a2699f3f9ff1753ba3a22ebbb958e607c406
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
