### PR TITLE
Kc metamask loginconnect error

### PR DESCRIPTION
**Pull request by kcheli**
Added code to connected() for MetaMask login & HealthNexusWallet Connect popups. Minor spelling corrections.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 81665d03b3846252fd05270c8f691a514ca15514
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f36349e18c2df6d36ae51efe094e260f3e7ac773
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 2744a50315dd7f3970f652729d6211020522bfe6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: b9b796e863a894ed83fd9d8870af373e121600b2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 81665d03b3846252fd05270c8f691a514ca15514
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f36349e18c2df6d36ae51efe094e260f3e7ac773
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 2744a50315dd7f3970f652729d6211020522bfe6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: b9b796e863a894ed83fd9d8870af373e121600b2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 88f64f9305e334f0ca83ae995d869f58f0c8119a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 81665d03b3846252fd05270c8f691a514ca15514
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f36349e18c2df6d36ae51efe094e260f3e7ac773
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 2744a50315dd7f3970f652729d6211020522bfe6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: b9b796e863a894ed83fd9d8870af373e121600b2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 88f64f9305e334f0ca83ae995d869f58f0c8119a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by lhendre** [comment]
@kcheli So a few things, please add back in the  docs/CNAME file with the line keymanager.simplyvitalhealth.com as is manually and push.  I am not sure why its being deleted on your end.  I fixed the merge conflicts but in the future make sure to merge in the latest updates and deal with conflicts.  After that, I can merge it in

**Comment by kcheli** [comment]
Got it. I’m not sure why it’s deleted either, I’ll take care of it.

On Jun 20, 2019, at 1:11 PM, lhendre <notifications@github.com> wrote:

@kcheli So a few things, please add back in the docs/CNAME file with the line keymanager.simplyvitalhealth.com as is manually and push. I am not sure why its being deleted on your end. I fixed the merge conflicts but in the future make sure to merge in the latest updates and deal with conflicts. After that, I can merge it in

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 81665d03b3846252fd05270c8f691a514ca15514
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f36349e18c2df6d36ae51efe094e260f3e7ac773
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 2744a50315dd7f3970f652729d6211020522bfe6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: b9b796e863a894ed83fd9d8870af373e121600b2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

 * Commit: 88f64f9305e334f0ca83ae995d869f58f0c8119a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 61a8cba5fb05010f440599a31eaedafd2c472e93
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c27073a061a3c3801505421113578239ed0ef656
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3d6bba69d68e8d6c6fd2945f1885d6664998fa8b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5d15c9d77db611127fb2a6656d9c02390e4dc5f8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by kcheli** [comment]
I pushed with the CNAME file added. Please let know if I've left something out. "docs/index.html" and "docs/404.html" should be there as well.

**Pull request merged**
