### PR TITLE
kc - feat keymanager: updated to Angular 8, web3-conditional welcome messages

### PR DESCRIPTION
**Pull request by kcheli**
1) updated to Angular 8
2) for Websocket, had to replace “this” with “window” (not ideal) - line 1, KeyManager/node_modules/websocket/lib/browser.js. 
3) made welcome page messages web3-conditional

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4d5b303f7e7d34d7e5ab4c41d2fcd2dd969b47d5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 510427f98452854d1b7b1efb52686284ff74d598
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fb67ae167369fb8c377dbaf02e28509368a21ba4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 052584a0dc1cbe2cf70a7772a7ccd5f9041d0644
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fd31fa84b0de32bbd7119bddf741b0666770fba9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 88f5f5437369c6f0c65f8be85bc8f2f4806118a6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 71146b107045e59c62bf49efcea571268f5a1d62
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 96c4d9ebf65c441c9c4e04f732e06f272f543c4a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 69fb0820cba7afc8bcab4e28856f2b809cc55d18
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Review by lhendre — COMMENTED** [review]
Overall this looks good, this is a large one and I'll need to test locally.  One potential issue I see is in the DRS.  You change some of the response types to 'json'  from array buffer.  The reason it was an array buffer was that the data can be a file.  I'll see if it still works without it but it is likely that part of the code will need to be worked on.  This will likely require you to get the gatekeeper up and running as well.  Schedule time with me next week to help you get it set up locally

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4d5b303f7e7d34d7e5ab4c41d2fcd2dd969b47d5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 510427f98452854d1b7b1efb52686284ff74d598
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fb67ae167369fb8c377dbaf02e28509368a21ba4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 052584a0dc1cbe2cf70a7772a7ccd5f9041d0644
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fd31fa84b0de32bbd7119bddf741b0666770fba9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 88f5f5437369c6f0c65f8be85bc8f2f4806118a6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 71146b107045e59c62bf49efcea571268f5a1d62
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 96c4d9ebf65c441c9c4e04f732e06f272f543c4a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 69fb0820cba7afc8bcab4e28856f2b809cc55d18
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 4d3cd4290280f7210922d96a72d8ae90dd3c76a0
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, bug, feature**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by lhendre** [comment]
@kcheli There are some conflicts, can you take a look at those first?

**Comment by kcheli** [comment]
Are the conflicts with the Angular 5 updated welcome message or with the
Angular 8 updates? I closed the Angular 8 pr and didn't notice conflicts
with the Angular 5 welcome message update.

**Pull request closed without merging**
