### PR TITLE
kc keymanager build

### PR DESCRIPTION
**Pull request by kcheli**
keymanager build

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00c4142463df05979cb552c1d6e9e69cfe156f25
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb4e8c386bbe71d6db4f5a4abad9c43ab5a6cf0d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 81665d03b3846252fd05270c8f691a514ca15514
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by lhendre** [comment]
There is some weird stuff goin on with this, I am going to wrap it up real quick, good work never the less.

**Pull request closed without merging**
