### PR TITLE
kc_metamaskstarterror

### PR DESCRIPTION
**Pull request by kcheli**
fixed MetaMask start error (missing web3)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c7aa31ac5983885d80995c3a1362a1fe9902da37
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f14b5da834dfae7f73ea8da1e8d1eaaf04e6177a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Comment by lhendre** [comment]
Remove package lock.json

**Comment by lhendre** [comment]
And remove the extra blank spaces and remove let a=true

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c7aa31ac5983885d80995c3a1362a1fe9902da37
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f14b5da834dfae7f73ea8da1e8d1eaaf04e6177a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d9ae54ac4412f0ba5a2fee85774406fa0c3d2b17
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/Health-Nexus/KeyManager

---
This message was auto-generated by https://gitcop.com

**Review by lhendre — APPROVED** [review]

**Pull request merged**
